# Generated by Django 5.2.1 on 2025-05-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='scheme',
            field=models.CharField(choices=[('BBBP', 'Beti Bacho Beti Padau'), ('SBA', 'Swach Bharat Abhiyan'), ('NIL', 'General')], default='NIL', max_length=50),
        ),
    ]
