# Generated by Django 5.2.1 on 2025-05-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemesapp', '0004_feedbackreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FeedbackReply',
        ),
    ]
