# Generated by Django 5.2.1 on 2025-05-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemesapp', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('benefits', models.TextField()),
                ('agency', models.CharField(max_length=255)),
                ('full_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
