# Generated by Django 5.2.1 on 2025-05-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemesapp', '0007_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='below_poverty_line',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='caste',
            field=models.CharField(blank=True, choices=[('G', 'General'), ('OBC', 'Other Backward Caste(OBC)'), ('PVTG', 'Particularly Vulnarable Tribal Group'), ('SC', 'Scheduled Class'), ('ST', 'Scheduled Tribe')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='disability',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='income',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='location',
            field=models.CharField(blank=True, choices=[('rural', 'Rural'), ('urban', 'Urban')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='maritial_status',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='minority',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
