# Generated by Django 5.2.1 on 2025-05-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemesapp', '0008_scheme_age_scheme_below_poverty_line_scheme_caste_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='date_of_birth',
        ),
    ]
