# Generated by Django 5.2.1 on 2025-05-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemesapp', '0009_remove_scheme_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=50)),
                ('age', models.IntegerField()),
                ('maritial_status', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=50)),
                ('location', models.CharField(choices=[('rural', 'Rural'), ('urban', 'Urban')], max_length=100)),
                ('caste', models.CharField(choices=[('G', 'General'), ('OBC', 'Other Backward Caste(OBC)'), ('PVTG', 'Particularly Vulnarable Tribal Group'), ('SC', 'Scheduled Class'), ('ST', 'Scheduled Tribe')], max_length=100)),
                ('disability', models.BooleanField()),
                ('minority', models.BooleanField()),
                ('below_poverty_line', models.BooleanField()),
                ('income', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
