# Generated by Django 5.2.1 on 2025-05-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemesapp', '0011_userdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='maritial_status',
            field=models.CharField(blank=True, choices=[('MARRIED', 'Married'), ('NOT MARRIED', 'Never Married'), ('WIDOWED', 'Widowed'), ('DIVORCEE', 'Divorcee')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='maritial_status',
            field=models.CharField(choices=[('MARRIED', 'Married'), ('NOT MARRIED', 'Never Married'), ('WIDOWED', 'Widowed'), ('DIVORCEE', 'Divorcee')], max_length=50),
        ),
    ]
