# Generated by Django 5.2.1 on 2025-05-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemesapp', '0014_alter_userdetails_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='age',
            new_name='min_age',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='income',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
