# Generated by Django 5.2.1 on 2025-05-23 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemesapp', '0015_rename_age_scheme_min_age_alter_userdetails_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemesapp.scheme'),
        ),
    ]
