# Generated by Django 5.2.1 on 2025-05-23 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemesapp', '0016_alter_feedback_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schemesapp.scheme'),
        ),
    ]
