# Generated by Django 5.2.1 on 2025-05-23 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemesapp', '0018_alter_feedback_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schemesapp.scheme'),
        ),
    ]
