# Generated by Django 5.2.1 on 2025-05-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemesapp', '0019_notification_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_aadhaar', models.BinaryField(db_column='aadhaar_encrypted')),
            ],
        ),
    ]
