# Generated by Django 5.2.1 on 2025-05-24 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemesapp', '0022_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='income',
            new_name='max_income',
        ),
    ]
