# Generated by Django 5.2.1 on 2025-05-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemesapp', '0023_rename_income_scheme_max_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='max_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
