# Generated by Django 5.2.1 on 2025-05-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemesapp', '0024_scheme_max_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='below_poverty_line',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='disability',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='max_income',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='minority',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
